import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lemonbrush = localFont({
  src: "./fonts/lemon-brush/LemonBrushArabicPersonalUseOnly-Regular.otf",
  variable: "--font-lemonbrush",
  weight: "400",
  style: "normal",
  display: "swap",
});

const tufuli = localFont({
  src: "./fonts/tufuli/TufuliArabicDEMO-Regular.otf",
  variable: "--font-tufuli",
  weight: "400",
  style: "normal",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // 3. ADD YOUR VARIABLES HERE
      className={` ${lemonbrush.variable} ${tufuli.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
